[build]
  command = "npm run build"
  publish = ".next"

[build.environment]
  NODE_VERSION = "18"
  NEXT_PUBLIC_API_URL = "https://masapp-backend.onrender.com/api"
  NEXT_PUBLIC_FRONTEND_URL = "https://restxqr.com"

# API routes için Netlify Functions
[[redirects]]
  from = "/api/subdomains/validate/*"
  to = "/.netlify/functions/subdomain-validate"
  status = 200

# Business pages - ONLY static HTML files, NOT Next.js pages
[[redirects]]
  from = "/business/login"
  to = "/business/login/index.html"
  status = 200
  force = true
[[redirects]]
  from = "/business/kitchen"
  to = "/business/kitchen/index.html"
  status = 200
  force = true
[[redirects]]
  from = "/business/waiter"
  to = "/business/waiter/index.html"
  status = 200
  force = true
[[redirects]]
  from = "/business/cashier"
  to = "/business/cashier/index.html"
  status = 200
  force = true

# Business dashboard uses Next.js - no redirect needed

# Frontend routing - SPA için
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
