[build]
  command = "npm run build"
  publish = ".next"

[build.environment]
  NODE_VERSION = "18"
  NEXT_PUBLIC_API_URL = "https://masapp-backend.onrender.com/api"
  NETLIFY_NEXT_PLUGIN_SKIP = "false"

# API routes için Netlify Functions
[[redirects]]
  from = "/api/subdomains/validate/*"
  to = "/.netlify/functions/subdomain-validate"
  status = 200

# SPA routing - all routes serve index for client-side routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
