services:
  - type: web
    name: restxqr-backend
    env: node
    rootDir: /
    buildCommand: npm run render-build
    startCommand: npm run render-start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
